import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from '../components/providers/StoreProvider';
import GlobalProgressBar from '@/components/ui/GlobalProgressBar';
import { ThemeProvider } from '@/components/ui/ThemeProvider';
import { ToastProvider } from '@/context/ToastContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Podium App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/podiumlogo1.png', // Light mode logo
        media: '(prefers-color-scheme: light)',
      },
      {
        url: '/podiumlogo2.png', // Dark mode logo
        media: '(prefers-color-scheme: dark)',
      },
    ],},
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <StoreProvider>
          <GlobalProgressBar />
          <ThemeProvider>
            <ToastProvider>
            {children}
            </ToastProvider>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}