import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from '../components/providers/StoreProvider';
// LayoutWrapper ko yahaan se hata dein

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Podium App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}